#!/bin/sh

# Copyright (C) 2021, Bayerische Motoren Werke Aktiengesellschaft (BMW AG),
#   Author: Alexander Domin (Alexander.Domin@bmw.de)
# Copyright (C) 2021, ProFUSION Sistemas e Soluções LTDA,
#   Author: Gabriel Fernandes (g7fernandes@profusion.mobi)
#
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL was
# not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.

# shellcheck disable=SC2046
unset $(git rev-parse --local-env-vars)

BASE_PATH="$(git rev-parse --show-toplevel)"
LIB_VSS_PATH="$BASE_PATH"
CLANG_TIDY="clang-tidy"

generate_compile_commands() {
  if [ ! -e "$LIB_VSS_PATH/build/compile_commands.json" ]; then
    if [ -d "$LIB_VSS_PATH/build" ] && ! [ -w "$LIB_VSS_PATH/build" ]; then
      printf "\033[41m The folder %s/build doens't have write permision\033[0m\n" "$LIB_VSS_PATH"
      return 1
    fi

    if cmake -DCMAKE_CXX_COMPILER=$(which clang++) -B"$LIB_VSS_PATH"/build -S"$LIB_VSS_PATH"; then
      printf "\033[41mIt was not possible generate the file compile_comands.json\033[0m\n"
      return 1
    fi
  fi
  return 0
}

call_clang_tidy() {
  staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep "[.]\(cpp\|h\|hpp\)$" | grep -v '/generated/')

  num_staged_files=0
  if [ -n "${staged_files}" ]; then
    num_staged_files=$(printf "%s\n" "$staged_files" | wc -l)
  fi

  echo "Linting ${num_staged_files} C++ files with clang-tidy"

  if [ "${num_staged_files}" -gt 0 ]; then
    i=1
    echo "${staged_files}" | while IFS= read -r file; do
      printf "\033[1m[%3d/%d] clang-tidy %s\033[0m\n" ${i} "${num_staged_files}" "$file"
      r="$($CLANG_TIDY -checks="$LIB_VSS_PATH"/.clang-tidy -p="$LIB_VSS_PATH"/build/compile_commands.json "$BASE_PATH"/"$file" 2>/dev/null)"
      if [ -n "${r}" ]; then
        printf "\033[41mERRORS:\033[0m %s\n" "$file"
        echo "$r"
        printf "\033[41mCLANG-TIDY:\033[0m Fix clang-tidy errors and try again\n"
        return 1
      fi
      i=$((i + 1))
    done || exit 1
  fi

  printf "\033[42mCLANG-TIDY SUCCEEDED\033[0m\n"
  return 0
}

generate_compile_commands &&
call_clang_tidy
